initial datawarehouse query with comments
sobibence/evConsumptionPredictionAAU pull request #1
Opened 2023-10-01 17:27 UTC by Malthe122

2023-10-02 11:38 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TABLE consumption (
make this into fact. Reintroduce outcommented attributes

2023-10-02 11:43 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TABLE vehicle (
rename to vehicle_trip_status. Contain attributes that will be identical throughout the whole trip (like additional car load)

2023-10-02 11:44 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TYPE road_quality_type AS ENUM ('bad', 'medium', 'good');
should be int range, if we can even fetch this data from anywhere

2023-10-02 11:44 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TYPE battery_size_type AS ENUM ('small', 'medium', 'large');
should be kilowatt size (float or int)

2023-10-05 10:21 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TABLE vehicle (
Done

2023-10-05 10:22 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TYPE road_quality_type AS ENUM ('bad', 'medium', 'good');
Done

2023-10-05 10:22 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TABLE consumption (
Done

2023-10-05 10:22 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +CREATE TYPE battery_size_type AS ENUM ('small', 'medium', 'large');
Done

2023-10-05 18:38 UTC, jokerofun commented on datawarehouse/intialBuild.sql
> +	wind_direction varchar(2),
Why varchar(2)? How do we represent the direction with only two characters?
I would expect strings such as "north", "south", etc.

2023-10-05 18:40 UTC, jokerofun commented on datawarehouse/intialBuild.sql
> +);
How about humidity? I believe that it has some impact on the battery life.

2023-10-05 18:47 UTC, jokerofun commented on datawarehouse/intialBuild.sql
> +	energy_consumption_Kwh float,
I see that we have another fact table "fact_consumption" which has an "energy_use" column. Does it make sense to have the same column in this fact table?

2023-10-09 13:19 UTC, sobibence requested changes

2023-10-09 13:19 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	additional_weight_grams int,
i think it should be in kilogramms

2023-10-09 13:19 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +CREATE TABLE timestamp (
we dont need this table better to use the postgres timestamp type

2023-10-09 13:19 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	frontal_size int,
float

2023-10-09 13:19 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	drag_coefficient int,
float

2023-10-09 13:19 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	weight_gram int,
also in kg

2023-10-10 06:11 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	energy_consumption_Kwh float,
I believed we discussed this at project meeting yesterday. Will leave it unresolved, so you can determine it

2023-10-10 06:15 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	drag_coefficient int,
you marked 3 lines of code, but you mean the drag_coefficient right?

2023-10-10 06:15 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	frontal_size int,
made frontal_size a float

2023-10-10 08:07 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	edge_id int,
this should be a reference to the edge table

2023-10-10 08:08 UTC, sobibence requested changes

2023-10-10 08:08 UTC, sobibence commented on datawarehouse/intialBuild.sql
> +	edge_id int,
this also should be a refence

2023-10-10 08:54 UTC, sobibence approved these changes

2023-10-16 09:19 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	energy_consumption_Kwh float,
i will change it to wh

2023-10-16 09:19 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	energy_consumption_Kwh float,
rename the other one to have the same name

2023-10-16 09:23 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	latitude float,
make these doubles

2023-10-16 09:29 UTC, merged

2023-10-19 16:57 UTC, Malthe122 commented on datawarehouse/intialBuild.sql
> +	edge_id int,
Done